function scriptFile = mjsWriteDockerRunScript(job, varargin)
% Write a shell script that will invoke a given job in Docker.
%
% This saves us from having to write lots of Docker syntax by hand.  This
% assumes we're working with the conventions established in the Docker
% image ninjaben/mjs-base.
%
% It should be the case that you can copy the generated scriptFile and
% jobFile to another host and run them.  The host must have Matlab
% and Docker installed.  The rest should "just work".  At least, that is
% the goal.
%
% scriptFile = mjsWriteDockerRunScript(job, varargin)
%
% 2016-2017 Brainard Lab, University of Pennsylvania

parser = inputParser();
parser.KeepUnmatched = true;
parser.addRequired('job', @isstruct);
parser.addParameter('scriptFile', '', @ischar);
parser.addParameter('dockerImage', 'ninjaben/mjs-base', @ischar);
parser.addParameter('dockerOptions', '--rm', @ischar);
parser.addParameter('dockerNetwork', '--net=host', @ischar);
parser.addParameter('mountDockerSocket', false, @islogical);
parser.addParameter('toolboxToolboxFlavor', '', @ischar);
parser.addParameter('toolboxToolboxDir', '', @ischar);
parser.addParameter('toolboxesDir', '', @ischar);
parser.addParameter('projectsDir', '', @ischar);
parser.addParameter('toolboxHooksDir', '', @ischar);
parser.addParameter('matlabDir', '', @ischar);
parser.addParameter('javaDir', '', @ischar);
parser.addParameter('logDir', '', @ischar);
parser.addParameter('commonToolboxDir', '', @ischar);
parser.addParameter('inputDir', '', @ischar);
parser.addParameter('outputDir', '', @ischar);
parser.addParameter('workingDir', '', @ischar);
parser.parse(job, varargin{:});
job = parser.Results.job;
scriptFile = parser.Results.scriptFile;
dockerImage = parser.Results.dockerImage;
dockerOptions = parser.Results.dockerOptions;
dockerNetwork = parser.Results.dockerNetwork;
mountDockerSocket = parser.Results.mountDockerSocket;
toolboxToolboxFlavor = parser.Results.toolboxToolboxFlavor;
toolboxToolboxDir = parser.Results.toolboxToolboxDir;
toolboxesDir = parser.Results.toolboxesDir;
projectsDir = parser.Results.projectsDir;
toolboxHooksDir = parser.Results.toolboxHooksDir;
matlabDir = parser.Results.matlabDir;
javaDir = parser.Results.javaDir;
logDir = parser.Results.logDir;
commonToolboxDir = parser.Results.commonToolboxDir;
inputDir = parser.Results.inputDir;
outputDir = parser.Results.outputDir;
workingDir = parser.Results.workingDir;

% default workingDir is outputDir
if isempty(workingDir)
    workingDir = outputDir;
end

% default script name based on job name
if isempty(scriptFile)
    scriptFile = fullfile(tempdir(), 'mjs', 'scripts', [job.name '.sh']);
end

%% Make an embeddable version of the JSON.
jobJson = mjsSaveJob(job);
escapedJson = embeddableJson(jobJson);

%% Make sure script dir exists.
scriptDir = fileparts(scriptFile);
if ~isempty(scriptDir) && 7 ~= exist(scriptDir, 'dir')
    mkdir(scriptDir);
end

fid = fopen(scriptFile, 'w');
if -1 == fid
    error('mjsWriteDockerRunScript:fopen', ...
        'Could not open file <%s> for writing.', scriptFile);
end

try
    fprintf(fid, '#!/bin/sh\n');
    fprintf(fid, '## Begin script generated by mjsWriteDockerRunScript.m\n');
    
    %% Embed the job JSON in the script itself.
    fprintf(fid, '\n');
    fprintf(fid, '# embed the Matlab job as JSON\n');
    fprintf(fid, 'JOB_JSON="%s"\n', escapedJson);
    
    %% Find Matlab in the execution environment.
    if isempty(matlabDir)
        fprintf(fid, '\n');
        fprintf(fid, '# find where Matlab is installed, dynamically\n');
        fprintf(fid, 'MATLAB_LINK="$(which matlab)"\n');
        fprintf(fid, 'MATLAB_EXECUTABLE="$(readlink -f "$MATLAB_LINK")"\n');
        fprintf(fid, 'MATLAB_BIN_DIR="$(dirname "$MATLAB_EXECUTABLE")"\n');
        fprintf(fid, 'MATLAB_DIR="$(dirname "$MATLAB_BIN_DIR")"\n');
    else
        fprintf(fid, '\n');
        fprintf(fid, '# use Matlab installed here\n');
        fprintf(fid, 'MATLAB_DIR="%s"\n', matlabDir);
    end
    
    %% Find Java in the execution environment.
    if strcmp(javaDir, 'bundled')
        fprintf(fid, '\n');
        fprintf(fid, '# use the Java that comes with with Matlab\n');
        fprintf(fid, 'JAVA_HOME="/usr/local/MATLAB/from-host/sys/java/jre/glnxa64/jre"\n');
    elseif ~isempty(javaDir)
        fprintf(fid, '\n');
        fprintf(fid, '# use Java installed here\n');
        fprintf(fid, 'JAVA_HOME="%s"\n', javaDir);
    end
    
    %% Allow for controlled versions of toolboxtoolbox.
    if ~isempty(toolboxToolboxFlavor)
        fprintf(fid, '\n');
        fprintf(fid, '# specify a flavor of ToolboxToolbox to git checkout \n');
        fprintf(fid, 'TOOLBOX_TOOLBOX_FLAVOR="%s"\n', toolboxToolboxFlavor);
    end
    
    %% Allow for automatic pull of Docker image.
    if ~isempty(regexp(dockerImage, '\:latest$', 'once'))
        fprintf(fid, '\n');
        fprintf(fid, '# refresh the Docker image\n');
        fprintf(fid, 'docker pull "%s"\n', dockerImage);
    end
    
    %% Do docker run with options and job command.
    fprintf(fid, '\n');
    fprintf(fid, '# invoke "docker run" with lots of options \n');
    fprintf(fid, '# using conventions established in ninjaben/mjs-base\n');
    fprintf(fid, 'docker run %s %s \\\n', dockerOptions, dockerNetwork);
    fprintf(fid, '  -v "$MATLAB_DIR":/usr/local/MATLAB/from-host \\\n');
    
    if mountDockerSocket
        fprintf(fid, '  -v /var/run/docker.sock:/var/run/docker.sock \\\n');
    end
    
    if ~isempty(toolboxToolboxDir)
        fprintf(fid, '  -v "%s":/mjs/ToolboxToolbox \\\n', toolboxToolboxDir);
    end
    
    if ~isempty(toolboxesDir)
        fprintf(fid, '  -v "%s":/mjs/toolboxes \\\n', toolboxesDir);
    end
    
    if ~isempty(projectsDir)
        fprintf(fid, '  -v "%s":/mjs/projects \\\n', projectsDir);
    end
    
    if ~isempty(toolboxHooksDir)
        fprintf(fid, '  -v "%s":/mjs/toolboxHooks \\\n', toolboxHooksDir);
    end
    
    if ~isempty(logDir)
        fprintf(fid, '  -v "%s":/var/log/matlab \\\n', logDir);
    end
    
    if ~isempty(commonToolboxDir)
        fprintf(fid, '  -v "%s":/opt/toolboxes \\\n', commonToolboxDir);
    end
    
    if isempty(inputDir)
        fprintf(fid, '  -e "INPUT_DIR=/var/mjs" \\\n');
    else
        fprintf(fid, '  -e "INPUT_DIR=%s" \\\n', inputDir);
        fprintf(fid, '  -v "%s":"%s" \\\n', inputDir, inputDir);
    end
    
    if isempty(outputDir)
        fprintf(fid, '  -e "OUTPUT_DIR=/var/mjs" \\\n');
    else
        fprintf(fid, '  -e "OUTPUT_DIR=%s" \\\n', outputDir);
        fprintf(fid, '  -v "%s":"%s" \\\n', outputDir, outputDir);
    end
    
    if isempty(workingDir)
        fprintf(fid, '  -e "WORKING_DIR=/var/mjs" \\\n');
    else
        fprintf(fid, '  -e "WORKING_DIR=%s" \\\n', workingDir);
    end
    
    if ~isempty(javaDir)
        fprintf(fid, '  -e "JAVA_HOME=$JAVA_HOME" \\\n');
    end
    
    fprintf(fid, '  %s \\\n', dockerImage);
    fprintf(fid, '  -r "mjsRunJobAndExit(''$JOB_JSON'');"\n');
    
    fprintf(fid, '\n');
    fprintf(fid, '## End script generated by mjsWriteDockerRunScript.m\n');
    fprintf(fid, '\n');
    
    fclose(fid);
    
catch err
    fclose(fid);
    rethrow(err);
end

system(['chmod +x ' scriptFile]);


%% Format JSON so it can survive in a shell script and as a Matlab string.
function embeddable = embeddableJson(json)

% escape double quotes around JSON strings, for the shell interpreter
escaped = regexprep(json, '"', '\\"', 'all');

% double-up single quotes, for the Matlab interpreter
quoted = regexprep(escaped, '''', '''''', 'all');

% remove most whitespace for the Matlab interpreter
isWhiteSpace = isspace(quoted);
isSpaceCharacter = quoted == ' ';
toKeep = ~isWhiteSpace | isSpaceCharacter;

embeddable = quoted(toKeep);
